version: '3.8'

services:
  unijadvalbot:
    build: .
    container_name: unijadval_bot
    restart: unless-stopped
    volumes:
      - bot_data:/app/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - DATABASE_FILE=/app/data/schedules.db
      - SCHEDULE_TIME=${SCHEDULE_TIME:-07:30}
      - TIMEZONE=Asia/Tashkent
    env_file:
      - .env

volumes:
  bot_data:
